---
# ~/.vim/configs/yamllint-custom.yaml
#
# yamllint -c ~/.vim/configs/yamllint-custom.yaml
#
# yamllint version: 1.31.0
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  anchors: enable
  braces:
    level: warning
    max-spaces-inside: 1
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
    min-spaces-from-content: 1
  comments-indentation: false
  document-end: disable
  document-start:
    level: warning
  empty-lines: enable
  empty-values: disable
  float-values: disable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length:
    allow-non-breakable-inline-mappings: true
    level: warning
    max: 240
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
