#!/bin/bash
#
# .github/citools/python/python-setup-verify
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

declare -A python_cmds

python_cmds=(
	[python]=$(
		command -v python >&/dev/null
		echo "$?"
	)
	[pyenv]=$(
		command -v pyenv >&/dev/null
		echo "$?"
	)
	[pip]=$(
		command -v pip >&/dev/null
		echo "$?"
	)
)

main() {
	printf "Verifying Python Installation\n\n"

	print_ruler

	echo Running: source /etc/profile.d/python.sh
	source /etc/profile.d/python.sh || track_errors

	print_ruler

	for key in "${!python_cmds[@]}"; do
		if [[ ${python_cmds[${key}]} -ne 0 ]]; then
			printf "ERROR: command [%s] not found.\n" "${key}"
			((retval++))
		fi
	done

	if [[ ${retval} -ne 0 ]]; then
		return "${retval}"
	fi

	print_ruler

	show_tool_versions_python

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
