#!/bin/bash
#
# .github/citools/rust/rust-setup-verify
#

# shellcheck disable=SC1091
source ../../.github/citools/includes/wrapper-library || exit

declare -i retval=0

declare -A rust_cmds

rust_cmds=(
	[cargo]=$(
		command -v cargo >&/dev/null
		echo "$?"
	)
	[rustc]=$(
		command -v rustc >&/dev/null
		echo "$?"
	)
	[rustup]=$(
		command -v rustup >&/dev/null
		echo "$?"
	)
)

main() {
	for key in "${!rust_cmds[@]}"; do
		if [[ ${rust_cmds[${key}]} -ne 0 ]]; then
			printf "ERROR: command [%s] not found.\n" "${key}"
			((retval++))
		fi
	done

	if [[ ${retval} -ne 0 ]]; then
		return "${retval}"
	fi

	printf "Verifying Rust Installation\n\n"

	print_ruler

	show_tool_versions_rust

	print_ruler

	echo Exit code: "${retval}"
	return "${retval}"
}

time main "${@}"
