#!/usr/bin/env bash

if [[ ! -f go.mod ]]; then
	printf "ERROR: run this script from inside the experiment's project folder.\n"
	exit 1
fi

# shellcheck disable=SC1091
source ../env-setup.sh

declare go_target="pico"

# idealy the project should just have `pico.json` or both `pico.json` and `pico-w`.json
if [[ -f pico-w.json ]]; then
	go_target="pico-w"
fi

exec tinygo-edit --editor="${1:-vim}" --target="${go_target}" --wait
